@endpoint= https://9wh8d6n4xk.execute-api.us-east-1.amazonaws.com/prod


GET {{endpoint}}/hello/
###

POST {{endpoint}}/spaces/
Content-Type: application/json

{
    "location":"London",
    "name":"Ayomiku",
    "username":"Ayomiku Olatunji",
    "friend":"Obed"
}
###

GET {{endpoint}}/spaces?helloId=f803eb24-a79e-4995-922a-e53fdbe1af37
###