@endpoint= https://9wh8d6n4xk.execute-api.us-east-1.amazonaws.com/prod


GET {{endpoint}}/hello/
###

POST {{endpoint}}/spaces/
Content-Type: application/json

{
    "location":"Nigeria",
    "name":"Ayomiku",
    "username":"Ayomiku Olatunji",
    "friend":"Obed"
}
###

GET {{endpoint}}/spaces
###

PUT {{endpoint}}/spaces?helloId=f803eb24-a79e-4995-922a-e53fdbe1af37
Content-Type: application/json

{
    "location":"London house",
    "name":"Ayomiku",
    "username":"Ayomiku Olatunji",
    "friend":"Obed"
}
###


DELETE  {{endpoint}}/spaces?helloId=4ac75b65-ff3f-41c9-8b6f-a613e9073eb2
Content-Type: application/json

###